# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AlterField(
            model_name='ulogaosobe',
            name='IdOsobe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uloga', to='evidencija.Osoba'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
