# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0002_auto_20201118_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SifProjekta', models.CharField(max_length=100)),
                ('NazProjekta', models.CharField(max_length=20)),
                ('OpisProjekta', models.CharField(max_length=20)),
                ('DatPocetka', models.CharField(max_length=11)),
                ('DatZavrsetka', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUloge', models.CharField(max_length=100)),
                ('NazUloge', models.CharField(max_length=20)),
            ],
        ),
    ]
