# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0003_projekt_uloga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('PersonalId', models.CharField(max_length=11)),
            ],
        ),
    ]
