# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectCode', models.CharField(max_length=11)),
                ('PersonId', models.CharField(max_length=11)),
                ('RoleId', models.CharField(max_length=11)),
                ('AssignmentDate', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
                ('StartDate', models.CharField(max_length=20)),
                ('EndDate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Projekt',
        ),
        migrations.DeleteModel(
            name='Uloga',
        ),
        migrations.RemoveField(
            model_name='ulogaosobe',
            name='IdOsobe',
        ),
        migrations.DeleteModel(
            name='Osoba',
        ),
        migrations.DeleteModel(
            name='UlogaOsobe',
        ),
    ]
